apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gke-cicd-pipeline
  labels:
    app: cicd
description: cicd delivery pipeline

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'test'
description: 'test target'
run:
  location: 'projects/${PROJECT_ID}/locations/${REGION}'
