apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gke-cicd-pipeline
  labels:
    app: cicd
description: cicd delivery pipeline
serialPipeline:
  stages:
    - targetId: 'test'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'test'
description: 'test target'
run:
  location: 'projects/super-sandbox-434412/locations/us-east1/clusters/autopilot-cluster-1' #replace the last destination with the name of the cluster created and the region if it is changed from what is available here.
