name: ci

on:
  push:
   

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: 'Create Cloud Deploy delivery pipeline'
        run: |-
          gcloud deploy apply --file ./pipeline.yaml --region us-east1
      - name: Deploy using Google Cloud Deploy
        run: |
          gcloud deploy releases create release-$(date +%Y%m%d-%H%M%S) \
          --project=super-sandbox-434412 \
          --delivery-pipeline=gke-cicd-pipeline \
          --region=us-east1 \
          --images=your-app=gcr.io/super-sandbox-434412/spring:v1 \
          --description="Automated deployment from GitHub Action"
